name: "Deploy"
on:
    push:
        branches:
            - main
jobs:
    runs-on: docker://alpine:3.8

    steps:
        - name: "Baixar Código"
          uses: actions/checkout@v4
        
        - name: "Copiar Arquivos"
          uses: appleboy/scp-action@v0.1.7
          with:
            host: ${{ vars.HOST }}
              username: ${{ vars.USERNAME }}
              password: ${{ vars.PASSWORD }}
              port: ${{ vars.PORT }}
              source: "../../"
              target: "/var/www/lpbarros.com"