name: lpbarros.com deploy

on:
    push:
        branches: [main]
        workflow_dispatch: []
    
jobs:
    deploy-production:
        runs-on: alpine-linux
        enviroment:
            - name: Production
            - url: https://lpbarros.com/
        steps:
            name: Repo Checkout
            uses: action/checkout@v1
            name: Production Deployment
            uses: easingthemes/ssh-deploy@main
            with:
                SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
                ARGS: "-rlgDzvc --delete"
                SOURCE: "../../lpbarros.github.io"
                REMOTE_HOST: ${{vars.REMOTE_HOST}}
                REMOTE_USER: ${{vars.REMOTE_USER}}
                REMOTE_PORT: ${{vars.REMOTE_PORT}}
